#!/usr/bin/env bash


    echo "           .____      _____"
    echo "         __| _/_____ / ____\\____  ______"
    echo "        / __ |/ __ \\   __\\/_  _ \\/  ___/"
    echo "       / /_/ \\  ___/|  |   /  <_> )___ \\"
    echo "       \\____ |\\___  >__|   \\____/____  >"
    echo "            \\/    \\/                 \\/ "
    echo " == MY ARCH SETUP INSTALLER == "



#part1

echo "Installing DefOS..."
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 15/" /etc/pacman.conf
pacman --noconfirm -Sy archlinux-keyring networkmanager
loadkeys us
timedatectl set-ntp true
lsblk
echo "Enter the drive: "
read drive
cfdisk $drive 
echo "Enter EFI partition: "
read efipartition
mkfs.vfat -F 32 $efipartition

echo "Enter the root partition: "
read rootpartition
mkfs.ext4 $rootpartition


echo "Enter the home partition: "
read homepartition
mkfs.ext4 $homepartition

mkdir /mnt/home


read -p "Did you create more partitions? [y/n]" answer
if [[ $answer = y ]] ; then
 


read -p "Did you also create games partition? [y/n]" answer
if [[ $answer = y ]] ; then
  echo "Enter games partition: "
  read gamespartition
 mkfs.ext4 $gamespartition
 mkdir /mnt/games
 mount $gamespartition /mnt/games
fi

read -p "Did you also create WMs partition? [y/n]" answer
if [[ $answer = y ]] ; then
  echo "Enter WMs partition: "
  read wmpartition
 mkfs.ext4 $wmpartition
 mkdir /mnt/wms
 mount $wmpartition /mnt/wms
fi
fi

mount $rootpartition /mnt 
mount $homepartition /mnt/home
pacstrap /mnt base base-devel linux linux-firmware
genfstab -U /mnt >> /mnt/etc/fstab
sed '1,/^#part2$/d' `basename $0` > /mnt/arch_install2.sh
chmod +x /mnt/arch_install2.sh
arch-chroot /mnt ./arch_install2.sh
exit 

#part2

printf '\033c'
pacman -S --noconfirm sed
ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=us" > /etc/vconsole.conf
echo "Hostname: "
read hostname
echo $hostname > /etc/hostname
echo "127.0.0.1       localhost" >> /etc/hosts
echo "::1             localhost" >> /etc/hosts
echo "127.0.1.1       $hostname.localdomain $hostname" >> /etc/hosts
mkinitcpio -P
passwd
pacman --noconfirm -S grub efibootmgr os-prober
echo "Enter EFI partition: " 
read efipartition
mkdir /boot/efi
mount $efipartition /boot/efi 
grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=GRUB
sed -i 's/quiet/pci=noaer/g' /etc/default/grub
sed -i 's/GRUB_TIMEOUT=5/GRUB_TIMEOUT=0/g' /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg

pacman -S --noconfirm xorg-server xorg-xinit xorg-xkill xorg-xsetroot xorg-xbacklight xorg-xprop xorg-xrandr xorg-xset xorgproto xterm xwallpaper xxhash \
     noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-jetbrains-mono ttf-joypixels ttf-font-awesome ttf-dejavu \
     sxiv mpv ffmpeg imagemagick  \
     fzf xwallpaper python-pywal unclutter xclip maim \
     zip unzip unrar p7zip xdotool papirus-icon-theme brightnessctl  \
     dosfstools ntfs-3g git sxhkd fish pipewire net-tools \
     arc-gtk-theme alacritty lolcat neovim vim dash \
     xcompmgr libnotify dunst slock jq aria2 cowsay pacman-contrib  \
     dhcpcd connman wpa_supplicant rsync pamixer mpd ncmpcpp \
     xdg-user-dirs libconfig sddm alsa-utils exa \
     bluez bluez-utils feh plymouth flameshot ninja meson uthash

systemctl enable connman.service 
systemctl enable sddm
systemctl enable networkmanager
echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
echo "Enter Username: "
read username
useradd -m -G wheel -s /bin/fish $username
passwd $username
echo "Pre-Installation Finish Reboot now"
 ai3_path=/home/$username/arch_install3.sh
 sed '1,/^#part3$/d' arch_install2.sh > $ai3_path
 chown $username:$username $ai3_path
 chmod +x $ai3_path
 su -c $ai3_path -s /bin/sh $username
exit 

#part3
printf '\033c'
cd $HOME

# installing yay

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si 
cd ~


yay -S sddm-sugar-candy-git edex-ui-appimage brave-bin --noconfirm

# plymouth configuration


sudo sed -i '/^HOOKS=/ s/)$/ plymouth)/' /etc/mkinitcpio.conf

sudo mkinitcpio -p linux

sudo sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT=/ s/"$/ quiet splash"/' /etc/default/grub

sudo grub-mkconfig -o /boot/grub/grub.cfg

sudo plymouth-set-defaul-theme -R bgrt 

# setup sddm theme

sudo sed -i 's/^Current=.*/Current=sugar-candy/' /etc/sddm.conf

# cloning .dotfiles

git clone https://github.com/xDeFc0nx/dotfiles.git

# copyng the files 

cp -r ~/dotfiles/.config/* ~/.config
cp -r ~/dotfiles/Wallpapers/* ~/Wallpapers/
cp -r ~/dotfiles//scripts/* ~/scripts
cp -r ~/dotfiles/.xinitrc ~/.xinitrc
cp -r ~/dotfiles/.xsession ~/.xsession
sudo mkdir -p /usr/share/xsessions/
cp -r ~/dotfiles/dwm.dekstop /usr/share/xsessions/dwm.desktop


# dwm: Window Manager
 sudo make -C ~/.config/dwm/ clean install

# dmenu: Program Menu
 sudo make -C ~/.config/dmenu/ clean install

# slstatus: system status 

 sudo make -C ~/.config/slstatus/ clean install

# picom setup 
cd ~/.config/picom 
meson setup --buildtype=release build
ninja -C build install

cd ~

config config --local status.showUntrackedFiles no
exit
