#+TITLE: DEFOS
#+DESCRIPTION: A installation script to install defOS desktop on an Arch-based distro.
#+AUTHOR: Nehar Tale (DeFc0n)
#+PROPERTY: header-args :tangle defOS
#+STARTUP: showeverything

* TABLE OF CONTENTS :toc:
- [[#about-defos][About DEFOS]]
- [[#installing-defos][Installing defos]]
  - [[#installation-instructions][Installation instructions]]

* About defos
#+CAPTION: defos Scrot
#+ATTR_HTML: :alt defos scrot :title defos Scrot :align left

defos is the name that I have chosen for my installation script that will install arch-linux and deploy my config, my neovim config, as well as associated programs that are needed to create a proper "desktop" experience.  defos should work on Arch Linux or any Arch-based distribution.  The programs that will be installed include pdwm, slstatus, Fish and other programs.  defos is only for x86_64 architecture and will not work on ARM devices such as the Raspberry Pi.

* Installing defos
** Installation instructions
To install defos, you need to clone this repository and run the ~defos~ script.
#+begin_example
git clone https://github.com/xDeFc0nx/defos
cd defos/
./defos
#+end_example

